import { renderInlineText } from "./render.mjs";

const MAX_DOCUMENT_BYTES = 1024 * 1024;
const MAX_MODULE_DIAGRAMS = 30;
const MAX_SEQUENCE_DIAGRAMS = 20;
const MAX_SEQUENCE_PARTICIPANTS = 8;
const MAX_DIAGRAM_EDGES = 120;
const MAX_MERMAID_LABEL_CHARACTERS = 60;
const TRUNCATION_NOTICE = "> Warning: output reached the safety limit and was truncated.";
const MODEL_TRUNCATION_NOTICE = "> Note: the number of entries exceeded the generation cap; only the leading entries are included and the rest were truncated.";

function createWriter() {
  const chunks = [];
  const suffix = `\n${TRUNCATION_NOTICE}\n`;
  const budget = MAX_DOCUMENT_BYTES - Buffer.byteLength(suffix);
  let bytes = 0;
  let truncated = false;
  let exhausted = false;
  return {
    get exhausted() {
      return exhausted;
    },
    line(value = "") {
      if (exhausted) return false;
      const chunk = `${value}\n`;
      const chunkBytes = Buffer.byteLength(chunk);
      if (bytes + chunkBytes > budget) {
        truncated = true;
        exhausted = true;
        return false;
      }
      chunks.push(chunk);
      bytes += chunkBytes;
      return true;
    },
    lines(...values) {
      for (const value of values) {
        if (!this.line(value)) return false;
      }
      return true;
    },
    finish() {
      const content = chunks.join("");
      return truncated ? `${content}${suffix}` : content;
    },
  };
}

// Mermaid labels use an allowlist because escaping rules differ between Mermaid
// node shapes; anything outside the list becomes a space so hostile source
// identifiers cannot introduce quotes, fences, brackets, or directives.
function mermaidLabel(value, fallback = "unnamed") {
  const cleaned = String(value ?? "")
    .replace(/[^\p{L}\p{N} _.\-/:#*?]+/gu, " ")
    .replace(/\s+/gu, " ")
    .trim();
  const label = cleaned || fallback;
  if (label.length <= MAX_MERMAID_LABEL_CHARACTERS) return label;
  return `${label.slice(0, MAX_MERMAID_LABEL_CHARACTERS - 3)}...`;
}

function citation(evidence) {
  if (!evidence) return "";
  return `${renderInlineText(evidence.file)}:${evidence.line}`;
}

function confidenceNote(useCase) {
  return useCase.minConfidence >= 0.95
    ? `Confidence ${useCase.minConfidence.toFixed(2)}`
    : `Confidence ${useCase.minConfidence.toFixed(2)} (contains heuristic relationships; review manually)`;
}

const TRIGGER_LABELS = new Map([
  ["submits_to", "form submission"],
  ["links_to", "page link"],
  ["requests", "script request"],
]);
const ACCESS_LABELS = new Map([
  ["read", "read"],
  ["write", "write"],
  ["read-write", "read-write"],
]);
const ARRIVAL_LABELS = new Map([
  ["forwards_to", "forward"],
  ["redirects_to", "redirect"],
  ["includes", "include"],
  ["uses_tile", "Tiles composition"],
]);

export function renderUseCases(model) {
  const writer = createWriter();
  writer.lines(
    "# Use Case Specifications (UCS)",
    "",
    `> Generated by Legacy Code Atlas from the source index; ${model.stats.useCases} use cases across ${model.stats.modules} modules. Citations are project-relative path:line.`,
  );
  if (model.truncated) writer.lines("", MODEL_TRUNCATION_NOTICE);

  for (const module of model.modules) {
    if (writer.exhausted) break;
    writer.lines("", `## Module ${renderInlineText(module.name)}`, "");
    for (const useCase of module.useCases) {
      if (writer.exhausted) break;
      const source = citation(useCase.evidence);
      writer.lines(
        `### Use case: ${renderInlineText(useCase.route)}`,
        "",
        `- Source: ${source || "no direct evidence"}`,
        `- ${confidenceNote(useCase)}`,
      );
      if (useCase.triggers.length > 0) {
        writer.line("- Triggers:");
        for (const trigger of useCase.triggers) {
          const kind = TRIGGER_LABELS.get(trigger.kind) ?? trigger.kind;
          const ref = citation(trigger.evidence);
          writer.line(`  - ${kind} from page ${renderInlineText(trigger.pagePath)}${ref ? ` (${ref})` : ""}`);
        }
      } else {
        writer.line("- Triggers: no page entry found (possibly triggered by an external system or an unresolved dynamic call)");
      }
      writer.line("- Main flow:");
      for (const step of useCase.mainFlow) {
        const via = step.via ? ` (via ${renderInlineText(step.via)})` : "";
        const ref = citation(step.evidence);
        writer.line(`  ${step.index}. ${renderInlineText(step.nodeType)} ${renderInlineText(step.name)}${via}${ref ? `, evidence ${ref}` : ""}`);
      }
      if (useCase.flowTruncated) writer.line("  - (main flow exceeds the display limit and was truncated)");
      if (useCase.tables.length > 0) {
        writer.line("- Tables:");
        for (const table of useCase.tables) {
          writer.line(`  - ${renderInlineText(table.name)} (${ACCESS_LABELS.get(table.access) ?? table.access})`);
        }
      } else {
        writer.line("- Tables: no direct reads or writes found");
      }
      writer.line("");
    }
  }
  return writer.finish();
}

export function renderUiSpec(model) {
  const writer = createWriter();
  writer.lines(
    "# UI Specifications (UIS)",
    "",
    `> Generated by Legacy Code Atlas from the source index; ${model.stats.pages} pages. Citations are project-relative path:line.`,
  );
  if (model.truncated) writer.lines("", MODEL_TRUNCATION_NOTICE);

  for (const page of model.pages) {
    if (writer.exhausted) break;
    writer.lines("", `## Page ${renderInlineText(page.filePath)}`, "");
    if (page.visibleText) writer.line(`- Visible text: ${renderInlineText(page.visibleText)}`);
    if (page.fields.length > 0) {
      writer.line(`- Form fields: ${page.fields.map((field) => `\`${renderInlineText(field)}\``).join(", ")}`);
    } else {
      writer.line("- Form fields: none");
    }
    if (page.actions.length > 0) {
      writer.line("- Page actions:");
      for (const action of page.actions) {
        const kind = TRIGGER_LABELS.get(action.kind) ?? action.kind;
        const ref = citation(action.evidence);
        writer.line(`  - ${kind} -> ${renderInlineText(action.target)}${ref ? ` (${ref})` : ""}`);
      }
    } else {
      writer.line("- Page actions: none");
    }
    if (page.arrivals.length > 0) {
      writer.line("- Arrival paths:");
      for (const arrival of page.arrivals) {
        const kind = ARRIVAL_LABELS.get(arrival.kind) ?? arrival.kind;
        writer.line(`  - ${kind} from ${renderInlineText(arrival.fromType)} ${renderInlineText(arrival.from)}`);
      }
    }
  }
  return writer.finish();
}

function moduleFlowchart(module, writer) {
  const nodeIds = new Map();
  const lines = [];
  const edges = new Set();
  const idFor = (key, label, shapeOpen, shapeClose) => {
    let id = nodeIds.get(key);
    if (!id) {
      id = `n${nodeIds.size}`;
      nodeIds.set(key, id);
      lines.push(`  ${id}${shapeOpen}${mermaidLabel(label)}${shapeClose}`);
    }
    return id;
  };
  for (const useCase of module.useCases) {
    const routeId = idFor(`route:${useCase.route}`, useCase.route, "([", "])");
    for (const trigger of useCase.triggers) {
      const pageId = idFor(`page:${trigger.pagePath}`, trigger.pagePath, "[", "]");
      edges.add(`  ${pageId} -->|${mermaidLabel(trigger.kind)}| ${routeId}`);
    }
    for (const table of useCase.tables) {
      const tableId = idFor(`table:${table.name}`, table.name, "[(", ")]");
      edges.add(`  ${routeId} -->|${mermaidLabel(ACCESS_LABELS.get(table.access) ?? table.access)}| ${tableId}`);
    }
  }
  if (nodeIds.size === 0) return;
  writer.lines("", `## Module overview: ${renderInlineText(module.name)}`, "", "```mermaid", "flowchart LR");
  for (const line of lines) writer.line(line);
  for (const edge of [...edges].sort().slice(0, MAX_DIAGRAM_EDGES)) writer.line(edge);
  writer.lines("```");
}

function sequenceDiagram(useCase, writer) {
  const steps = useCase.mainFlow.slice(0, MAX_SEQUENCE_PARTICIPANTS);
  if (steps.length < 2) return;
  writer.lines("", `## Use case sequence: ${renderInlineText(useCase.route)}`, "", "```mermaid", "sequenceDiagram");
  steps.forEach((step, index) => {
    writer.line(`  participant P${index} as ${mermaidLabel(`${step.nodeType} ${step.name}`)}`);
  });
  for (let index = 1; index < steps.length; index += 1) {
    writer.line(`  P${index - 1}->>P${index}: ${mermaidLabel(steps[index].via ?? "calls")}`);
  }
  if (useCase.mainFlow.length > steps.length) {
    writer.line(`  Note over P${steps.length - 1}: remaining steps truncated`);
  }
  writer.lines("```");
}

export function renderDiagrams(model) {
  const writer = createWriter();
  writer.lines(
    "# System Diagrams (Mermaid)",
    "",
    "> Generated by Legacy Code Atlas from the source index; renders directly in Mermaid-capable Markdown viewers.",
  );
  if (model.truncated) writer.lines("", MODEL_TRUNCATION_NOTICE);

  const modules = model.modules.slice(0, MAX_MODULE_DIAGRAMS);
  if (model.modules.length > modules.length) writer.lines("", MODEL_TRUNCATION_NOTICE);
  for (const module of modules) {
    if (writer.exhausted) break;
    moduleFlowchart(module, writer);
  }

  const sequenced = [...model.useCases]
    .filter((useCase) => useCase.mainFlow.length >= 2)
    .sort((left, right) => right.mainFlow.length - left.mainFlow.length
      || (left.route < right.route ? -1 : left.route > right.route ? 1 : 0))
    .slice(0, MAX_SEQUENCE_DIAGRAMS);
  for (const useCase of sequenced) {
    if (writer.exhausted) break;
    sequenceDiagram(useCase, writer);
  }
  return writer.finish();
}
